# Site settings
title: My Coding Journey
header-img: img/home-bg.png
email: patsand24csu@yahoo.com
copyright_name: patsand24
description: > # this means to ignore newlines until "baseurl:"
  Learning How to Code From Scratch
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  patsand24
learn_profile: patsand24
email_username: patsand24csu@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
